Use `vars = {` instead of `vars {` to appease Terraform 0.13
Otherwise this happens:

```
Error: Unsupported block type

  on .terraform/modules/athena_lb_logs/data.tf line 7, in data "template_file" "main":
   7:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.
```